### ISSUE TITLE
Random.int suffers from bias

### ISSUE THREAD

**Issue by roobie** [jasononeil/hxrandom#1]
The implementation for getting a random `Int` suffers from a bias, which one can read about here http://blog.codinghorror.com/the-danger-of-naivete/

I'm not saying that the old implementation necessarily should be replaced, only that it could be relevant for this library.

Consider implementing a Fisher-Yates shuffle. For example code see https://gist.github.com/roobie/24a7f270dde1926ac5f5#file-random-hx-L59
based on https://bost.ocks.org/mike/shuffle/

**Comment by roobie** [comment]
Nah, I'm just being silly. However the `shuffle` function seems to be suffering from bias.

**Comment by player-03** [comment]
I've submitted a fix; see #4.
